[project]
name = "break_word_traps"
description = "AI microservice for BreakWordTraps"
version = "0.0.1"
readme = "README.md"
dependencies = [
  "fastapi",
  "python-multipart",
  "uvicorn",
  "uvloop",
  "typer",
  "rich",
]

[project.scripts]
bwt = "break_word_traps.entrypoint:cli"
